### ISSUE TITLE
SDK-1180 - 4me Connector - Show only required fields and mandatory fields first

### ISSUE THREAD

**Issue by bennettgo** [Workato-Partners/4me#10]
**Enhancement Requested**
When using the 4me Connector the user is overwhelmed by many fields and many of them aren’t required for instance to create a Product or a Configuration Item. 

The request is to make optional fields really optional in the UI to only show relevant fields by default.

**Comment by klaasvandeweerdt** [comment]
@bennettgo, as mentioned in issue #9.
> The UX shows mandatory fields if they are mandatory in the schema. Some of the fields are mandatory in specific scenario based on another selection. We are updating the GraphQL schema and set all fields mandatory where possible.
> To resolve this I defined a set of commonly used fields in the connector for which optional: true will be set, all other fields are default to optional: false unless they are mandatory.

**Comment by klaasvandeweerdt** [comment]
This has been resolved and was part of the latest pull request #13.
