### ISSUE TITLE
SDK-1179 - 4me Connector - Add helpful hints to connect page

### ISSUE THREAD

**Issue by bennettgo** [Workato-Partners/4me#11]
**Enhancement Requested**
Creating a connection to 4me requires to read & understand the 4me documentation, because it’s missing some simple to add and meaning full hints to the connect dialog.

First: What is the 4me instance and where do I find it? 
Second: When selecting a Auth-Method: Personal Access Token the hint should tell me where to find/create it.
Third: When selecting a Auth-Method: OAuth2 the hint should tell me where to find or create new OAuth Credentials

Right now, the hint provides are meaningless as they just repeat the title of the field.

**Comment by klaasvandeweerdt** [comment]
@bennettgo, I added the additional info and a link to our developer page for more detailed information.

**Comment by klaasvandeweerdt** [comment]
This has been resolved and was part of the latest pull request #13.
