### ISSUE TITLE
SDK-1177 - 4me Connector - Fields to retrieve doesn't return all fields

### ISSUE THREAD

**Issue by bennettgo** [Workato-Partners/4me#12]
**Current Behavior**
The connector states in the fields to retrieve:

Select the fields that must be retrieved to improve performance. All fields are returned if left blank.

This doesn’t work. If left blank nothing is returned at all and if you run into an error, you don’t realize/see the problem as long as you don’t request the error to be returned. 
This is very confusing the user, as he expects information to be returned.

**Expected Behavior**
When no fields to retrieve are provided, all fields should be returned as it’s documented in the UI.
Errors should be requested by default to make root-cause analysis more simple.

**Comment by klaasvandeweerdt** [comment]
@bennettgo, I checked it and this does work. All fields are returned if no fields are specified. If I run a query on `people` it returns me the `totalCount` which is the only field available for people. If you look a the pick list of available fields then there is only one available field for `people` which is `totalCount`. If you select `me`, which is not a connection it will load all fields if none are selected. All query objects are GraphQL connections, except for `me` and `account`, that support pagination, with only one property `totalCount`. To get the data you need to add a `Sub Query`. I will add additional info in the hint to explain this.

**Comment by klaasvandeweerdt** [comment]
This has been resolved and was part of the latest pull request #13.
