### ISSUE TITLE
SDK-1178 - 4me Connector does not fail on error response

### ISSUE THREAD

**Issue by bennettgo** [Workato-Partners/4me#7]
**Current Behavior**
The 4me Connector does not fail on received error responses which makes it very hard to design a properly working recipe.

![4me Action continues with erros](https://github.com/Workato-Partners/4me/assets/25265275/27ab772b-cede-45ed-9bb7-91ff4fd92d2e)

**Expected behaviour**
If an action fails on server-side it should also fail in the recipe to allow proper error-handling/workflow-control. 

For that the 4me connector must check, if an error object has been returned and handle it.

**Steps To Reproduce**
1. Create a scheduled recipe
2. Add Action: 4me and select action: Mutate records
3. Select Mutation: Product create
4. Provide a Brand, a Category and a Name
5. Run the recipe 2x with the same product name

**Comment by klaasvandeweerdt** [comment]
@bennettgo, this has been implemented. If the object contains an error object, only on mutations, it will always include it in the query. When the response contains one or more error message it will throw an error. I still have to complete the specs and will commit once completed.

**Comment by klaasvandeweerdt** [comment]
This has been resolved and was part of the latest pull request #13.
