### ISSUE TITLE
SDK-1182 - 4me Connector - Add Pick-Up lists

### ISSUE THREAD

**Issue by bennettgo** [Workato-Partners/4me#8]
**Enhancement Requested**
The 4me connector doesn’t provide Pick-Up lists for fields where it would be appropriate. Two examples where I would expect a Pick-Up/Select option:

Status of a Configuration item (or at least display the potential values as a hint)

Depreciation method of a Product

There might be many more situations and it should be reviewed in general where it makes sense to add a pick-list instead of a simple text-field to improve the UX.

**Comment by klaasvandeweerdt** [comment]
@bennettgo, the Pick-Up lists are generated based on the GraphQL schema. For many values like the configuration item status this is a string value and not an enum in GraphQL. This means I cannot convert them to a Pick-Up list but I will have to update our GraphQL schema with the possible values as it is for Depreciation method of a Product.
<img width="376" alt="image" src="https://github.com/Workato-Partners/4me/assets/44910658/ff8cfa79-1668-48e7-8845-f8d6de8347fa">

**Comment by klaasvandeweerdt** [comment]
@bennettgo, The inputs are `scalar` types and not `enum` but with the parsing of the description I was able to convert them to pick lists. At our end we implement specific specs to guarantee the format of those descriptions.

**Comment by klaasvandeweerdt** [comment]
This has been resolved and was part of the latest pull request #13.
