### ISSUE TITLE
SDK-1181 - 4me Connector - Mark mandatory fields

### ISSUE THREAD

**Issue by bennettgo** [Workato-Partners/4me#9]
**Enhancement Requested**
When creating a new Configuration Item I run an error because of the mandatory fields aren’t provided:
```
"errors": [
		{
			"message": "Label can't be blank"
		},
		{
			"message": "Support team can't be blank"
		}
	]
```
But these fields aren’t marked as required in the connector.

The request is to make mandatory fields `optional: false` in the connector to improve the UX.

**Comment by klaasvandeweerdt** [comment]
@bennettgo, the UX shows mandatory fields if they are mandatory in the schema. Some of the fields are mandatory in specific scenario based on another selection. We are updating the GraphQL schema and set all fields mandatory where possible.
To resolve this I defined a set of commonly used fields in the connector for which `optional: true` will be set, all other fields are default to `optional: false` unless they are mandatory.

**Comment by klaasvandeweerdt** [comment]
This has been resolved and was part of the latest pull request #13.
